name: onelocate
description: Introducing our innovative Location Fetching plugin called OneLocate, a powerful tool that allows you to check the device location without GPS.
version: 0.0.1
homepage: https://github.com/udithperera-dev/onelocate

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dio: ^5.4.0
flutter:
  plugin:
    platforms:
      android:
        package: com.akurupela.onelocate
        pluginClass: OnelocatePlugin
      ios:
        pluginClass: OnelocatePlugin

topics:
  - onelocate
  - android
  - ios
  - geo-location
  - without-gps